%% Task 2: Signal A vs Signal B Analysis
clear; clc; close all;
fs = 1000;
dt = 1/fs;
t1 = 0:dt:2-dt;
t2 = 2:dt:4-dt;
t  = [t1, t2];
N  = length(t);
sigA_part1 = sin(2 * pi * 10 * t1);
sigA_part2 = sin(2 * pi * 40 * t2);
x_A = [sigA_part1, sigA_part2];
sigB_part1 = sin(2 * pi * 40 * t1);
sigB_part2 = sin(2 * pi * 10 * t2);
x_B = [sigB_part1, sigB_part2];
f_axis = (0:N-1) * (fs / N);
X_A_fft = abs(fft(x_A)) / N;
X_B_fft = abs(fft(x_B)) / N;
f_limit = 60;
idx_limit = find(f_axis <= f_limit, 1, 'last');
figure('Name', 'Task 2: Time-Frequency Comparison (Signal A vs B)', 'Color', 'w', 'Position', [100, 50, 1200, 850]);
subplot(3, 2, 1);
plot(t, x_A, 'b', 'LineWidth', 1.2); hold on;
xline(2, 'k--', 'LineWidth', 2);
grid on;
title('\bf{1A. Signal A: Time Domain Waveform}', 'FontSize', 12, 'Color', 'b');
text(0.8, 1.4, '10 Hz', 'Color', 'b', 'FontSize', 12, 'FontWeight', 'bold');
text(2.8, 1.4, '40 Hz', 'Color', 'b', 'FontSize', 12, 'FontWeight', 'bold');
xlabel('Time (seconds)'); ylabel('Amplitude');
ylim([-1.8 1.8]); xlim([0 4]);
subplot(3, 2, 2);
plot(t, x_B, 'r', 'LineWidth', 1.2); hold on;
xline(2, 'k--', 'LineWidth', 2);
grid on;
title('\bf{1B. Signal B: Time Domain Waveform}', 'FontSize', 12, 'Color', 'r');
text(0.8, 1.4, '40 Hz', 'Color', 'r', 'FontSize', 12, 'FontWeight', 'bold');
text(2.8, 1.4, '10 Hz', 'Color', 'r', 'FontSize', 12, 'FontWeight', 'bold');
xlabel('Time (seconds)'); ylabel('Amplitude');
ylim([-1.8 1.8]); xlim([0 4]);
subplot(3, 2, 3);
plot(f_axis(1:idx_limit), X_A_fft(1:idx_limit), 'b', 'LineWidth', 1.5, 'Marker', 'o');
grid on;
title('\bf{2A. Signal A: FFT Spectrum}', 'FontSize', 12);
xlabel('Frequency (Hz)'); ylabel('Magnitude');
xlim([0 f_limit]); ylim([0 0.6]);
subplot(3, 2, 4);
plot(f_axis(1:idx_limit), X_B_fft(1:idx_limit), 'r', 'LineWidth', 1.5, 'Marker', 'o');
grid on;
title('\bf{2B. Signal B: FFT Spectrum}', 'FontSize', 12);
xlabel('Frequency (Hz)'); ylabel('Magnitude');
xlim([0 f_limit]); ylim([0 0.6]);
subplot(3, 2, 5);
[wt_A, f_A] = cwt(x_A, 'amor', fs);
surface(t, f_A, abs(wt_A));
shading interp;
axis tight;
colormap jet;
set(gca, 'YScale', 'log');
title('\bf{3A. Signal A: CWT Scalogram}', 'FontSize', 12);
xlabel('Time (seconds)'); ylabel('Frequency (Hz)');
ylim([1 100]);
cb1 = colorbar; cb1.Label.String = 'Magnitude';
subplot(3, 2, 6);
[wt_B, f_B] = cwt(x_B, 'amor', fs);
surface(t, f_B, abs(wt_B));
shading interp;
axis tight;
colormap jet;
set(gca, 'YScale', 'log');
title('\bf{3B. Signal B: CWT Scalogram}', 'FontSize', 12);
xlabel('Time (seconds)'); ylabel('Frequency (Hz)');
ylim([1 100]);
cb2 = colorbar; cb2.Label.String = 'Magnitude';

%% Task 3: Real Dataset Analysis (Loma Prieta Earthquake)
clear;
load quake;
x = e(1:4000);
fs = 200;
N = length(x);
t = (0:N-1) / fs;
figure('Name', 'Task 3: Real Data Analysis (Earthquake)', 'Color', 'w');
subplot(3, 1, 1);
plot(t, x, 'b', 'LineWidth', 1);
grid on;
title('\bf{1. Time Domain: Raw Earthquake Signal}');
xlabel('Time (seconds)');
ylabel('Acceleration');
xlim([0 max(t)]);
X_fft = abs(fft(x)) / N;
f_axis = (0:N-1) * (fs / N);
subplot(3, 1, 2);
plot(f_axis(1:floor(N/2)), X_fft(1:floor(N/2)), 'r', 'LineWidth', 1.2);
grid on;
title('\bf{2. Fast Fourier Transform (FFT) Spectrum}');
xlabel('Frequency (Hz)');
ylabel('Magnitude');
xlim([0 50]);
subplot(3, 1, 3);
[wt, f] = cwt(x, 'amor', fs);
surface(t, f, abs(wt));
shading flat;
axis tight;
colormap jet;
c = colorbar;
c.Label.String = 'Magnitude';
set(gca, 'YScale', 'log');
title('\bf{3. Continuous Wavelet Transform (CWT Scalogram)}');
xlabel('Time (seconds)');
ylabel('Frequency (Hz)');
ylim([1 50]);